---
release:
  prerelease: auto
archives:
  - replacements:
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
before:
  hooks:
    - "go mod tidy"
    - "go generate ./..."
builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
      - arm
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm
    main: ./cmd/zeet
changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  sort: asc
checksum:
  name_template: checksums.txt
project_name: zeet
snapshot:
  name_template: "{{ incpatch .Version }}-next"
brews:
  - name: zeet
    tap:
      owner: zeet-dev
      name: homebrew-tap
      token: "{{ .Env.GORELEASER_GITHUB_TOKEN }}"

    homepage: "https://zeet.co"
    description: "The Zeet CLI"
    skip_upload: auto

    custom_block: |
      head "https://github.com/zeet-dev/cli.git"
  - name: zeet-rc
    tap:
      owner: zeet-dev
      name: homebrew-tap
      token: "{{ .Env.GORELEASER_GITHUB_TOKEN }}"
    homepage: "https://zeet.co"
    description: "The Zeet CLI [w/ release candidates]"
    install: |
      bin.install "zeet" => "zeet-rc"
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "docker.io/zeetdev/cli:{{ .Version }}-amd64"
      - "docker.io/zeetdev/cli:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "docker.io/zeetdev/cli:{{ .Version }}-arm64"
      - "docker.io/zeetdev/cli:latest-arm64"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
docker_manifests:
  - name_template: docker.io/zeetdev/cli:{{ .Version }}
    image_templates:
      - docker.io/zeetdev/cli:{{ .Version }}-amd64
      - docker.io/zeetdev/cli:{{ .Version }}-arm64
  - name_template: docker.io/zeetdev/cli:latest
    image_templates:
      - docker.io/zeetdev/cli:{{ .Version }}-amd64
      - docker.io/zeetdev/cli:{{ .Version }}-arm64
