fragment ClusterDetailV1 on Cluster {
  id

  displayName

  state
  connected

  cloudProvider

  createdAt
  updatedAt
}

query clusterDetails($teamId: UUID!, $clusterId: UUID!) {
  team(id: $teamId) {
    id
    cluster(id: $clusterId) {
      id
      ...ClusterDetailV1
    }
  }
}

query clusterRevisions($teamId: UUID!, $clusterId: UUID!) {
  team(id: $teamId) {
    id
    cluster(id: $clusterId) {
      id
      configurationRevisions {
        nodes {
          ...RevisionDetailV1
        }
      }
    }
  }
}

query clusterStatus($teamId: UUID!, $clusterId: UUID!) {
  team(id: $teamId) {
    id
    cluster(id: $clusterId) {
      id
      status
    }
  }
}
